# Generated by Django 5.1.3 on 2024-12-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0003_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=17)),
            ],
        ),
        migrations.RenameModel(
            old_name='table_details',
            new_name='details_table',
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
