# Generated by Django 5.1.3 on 2024-12-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0004_register_table_rename_table_details_details_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_table',
            name='country',
        ),
    ]
