# Generated by Django 5.1.3 on 2024-12-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0006_details_table_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details_table',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
