# Generated by Django 5.1.3 on 2024-12-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0007_alter_details_table_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_table',
            name='cur_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='details_table',
            name='cur_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
